### ISSUE TITLE
Specify the preferred server to download from when configuring a provider

### ISSUE THREAD

**Issue by ShiraazMoollatjie** [anime-dl/anime-downloader#116]
So today I tried to download from the 9anime provider, but I found that the rapidvideo links were all disabled/not working and this causes the `anime dl` command to fail for that provider.

Specifically for 9anime, you get four different servers to download from (Rapidvideo, MyCloud, Mp4Upload and Openload). So for the moment, I can watch all episodes on the MyCloud server, but I don't know how to do this with `anime dl` command.

Is there no way to either choose the preferred download server or to fallback to the other servers when the downloads are not working for a provider?

**Comment by rehtlaw** [comment]
essentially same as #32
