### ISSUE TITLE
AnimeUltima.to Support

### ISSUE THREAD

**Issue by DarkKnight1995** [anime-dl/anime-downloader#325]
**Describe the feature here**
Kindly add support for AnimeUltima.to , it has bothe dubbed and subbed versions with resolutions ranging from 240p to 1080p.

**Comment by Blatzar** [comment]
Both cfscrape and cloudscraper are throwing errors when scraping AnimeUltima making scraping impossible (due to cloudflares wait 5 seconds page). I wouldn't bet on it getting added anytime soon.
