### ISSUE TITLE
Kissanime is dead but clone sites have been found!

### ISSUE THREAD

**Issue by AbdullahM0hamed** [anime-dl/anime-downloader#472]
As our dear friend (I use the term loosely) @Blatzar said: "Wont remove the site file in case copies gets made" (in #470, in reference to removing the redundant kissanime files), we should add copies when they're made! 

Rejoice, for copies already exist! Here are two (isn't this great, I hope you are as pleased as I am!):
°https://kiss-anime.ws
°https://kissanime.nz

Make every bit of code count!

Yours entirely insincerely, someone who wishes you would delete the kissanime code.

**Comment by MichaelDavidJohnson** [comment]
All dead sites .py files should be removed from main release unless someone has planned to revamp the site - given that kissanime is gone, it should be removed from the project... However, this (for some reason) is not standard practice for this project. 

Thank you for providing kiss clones, I'll see if I can get something going on those in my free time.

**Comment by ayourk** [comment]
https://kissanime.nz has moved to https://kissanime.ac
