### ISSUE TITLE
Fiverr Guy on animeflv

### ISSUE THREAD

**Issue by IguanasInPyjamas** [anime-dl/anime-downloader#555]
Just run the following command;
`` anime dl "naruto" -e 1 --provider animeflv --play mpv ``

Instead of getting the lovely orange haired protagonist that we all know and came to love... we instead have a guy using a bad green screen with 20 second audio desync. Apparently, Clannad seems to work. There seems to be an issue with the streamtape (stape) server. Different servers need to be changed.

**Comment by nate-moo** [comment]
yeet goes the source
