### ISSUE TITLE
Upload new version of anime-downloader to the pypi

### ISSUE THREAD

**Issue by bonkboykz** [anime-dl/anime-downloader#563]
Hi,

Since the recommended way of installing the `anime-downloader` is through `brew` I want to update the formulae for it, because it has outdated version of `4.6.6`.

However, to do so, we might need to update the package in the [pypi repository](https://pypi.org/project/anime-downloader/), which has version of `4.6.8`.

Could someone upload the new version, so I could update the brew's formulae?

**Comment by IguanasInPyjamas** [comment]
Yes, I've been trying to get access to the pypi so I can push the update to it. To no avail. For now, just pull directly via git.

**Comment by bonkboykz** [comment]
I want to install latest version from `brew`. Right now formulae has `4.6.6` https://github.com/Homebrew/homebrew-core/blob/master/Formula/anime-downloader.rb#L6 which brew pulls from pypi.

Could we, perhaps, contact @vn-ki, since they appear to be the author of the pypi?

**Comment by IguanasInPyjamas** [comment]
Got access to it, 5.0.1 has been pushed.
