### ISSUE TITLE
[Qustion]Where is the FastStream class

### ISSUE THREAD

**Issue by C0nvert** [anime-dl/anime-downloader#584]
Hello Guys,
The Programm takes the "FastStream" Server from the config but I'm interested in where the FastStream class itself is.
I couldn't find it.
Cause Animeflix is only working with FastStream and i'd like to write a Kodi Addon for it and didn't find a working API.

**Comment by IguanasInPyjamas** [comment]
They return no extractor so I believe it's all in sites/animeflix.py
