### ISSUE TITLE
Launch options for mpv

### ISSUE THREAD

**Issue by akash-258** [anime-dl/anime-downloader#589]
Plz, tell me how can I launch MPV with a specific profile for "anime watch". Currently, it uses the default profile but I want it to launch with something like " mpv --profile=anime4k "

**Comment by IguanasInPyjamas** [comment]
there's no mpv args being handled, can you not set default behaviour in mpv? I may look into adding this

**Comment by akash-258** [comment]
I cannot add the 'anime4k' shader in the default config because it will affect other normal videos as well. So I set the shaders in input.conf but using that I have to activate the shader using that key in every episode I watch. So I was thinking of a way so that I can launch MPV with a --profile option, that way the shader will only work in anime watch.
Please implement this feature in some upcoming release as it will be really helpful or tell me some way it could be done in the current release.

**Comment by akash-258** [comment]
And maybe the "anime4k" shader can be added to our wonderful application itself, which can be activated with a keypress.

**Comment by theCow61** [comment]
There seems to be a "mpv-config.conf" in .config/anime-downloader folder though every time I edit it, my changes get overwrited but I think thats a good place to start for figuring this out and from the looks of it you can mess with key bindings in it.

**Comment by 0kalekale** [comment]
@IguanasInPyjamas
> there's no mpv args being handled, can you not set default behaviour in mpv? I may look into adding this

how about this:
define mpv args/flags somewhere in ~/.conifg/anime-downloader/config.json
```js
{
"mpv-args":
 [
    {"arg" : "--profile=anime4k"},
    {"arg" : "--slang=eng"}
 ]
}
```
and when you call ```anime watch <something>``` the args get passed into mpv from the config file

**Comment by 0kalekale** [comment]
@theCow61

> There seems to be a "mpv-config.conf" in .config/anime-downloader folder though every time I edit it, my changes get overwrited but I think thats a good place to start for figuring this out and from the looks of it you can mess with key bindings in it.

from [anime_downloader/players/mpv.py](https://github.com/anime-dl/anime-downloader/blob/master/anime_downloader/players/mpv.py):

```py
def get_mpv_configfile():
    # Read the user's input config file if it exists
    userconf = os.path.join(get_mpv_home(), 'input.conf')
    userconftext = ''
    if os.path.exists(userconf):
        with open(userconf, 'r') as userconfigfile:
            userconftext = userconfigfile.read()

    # Create a new config file to add anime-downloader specific key bindings
    conf = os.path.join(config.APP_DIR, 'mpv-config.conf')
    with open(conf, 'w') as configfile:
        configfile.write(
            userconftext +
            'q quit 50\nCLOSE_WIN quit 50\nSTOP quit 50\nctrl+c quit 50\n'
            '> quit 51\nNEXT quit 51\n< quit 52\nPREV quit 52\ni seek 80\n'
        )

    return conf
```

it seems the mpv-config.conf is  for the [input config](https://mpv.io/manual/stable/#input), so if you dont have input.conf already, it overwrites it.

**Comment by theCow61** [comment]
Figured out a solution, gonna implement this feature and do my first commit for this project hopefully I can get this done by today but it shouldn't take to long.

**Comment by theCow61** [comment]
With this commit you should be able to add launch arguments though I am planning on making this more advanced in the future and expand on this.

**Comment by theCow61** [comment]
> I cannot add the 'anime4k' shader in the default config because it will affect other normal videos as well. So I set the shaders in input.conf but using that I have to activate the shader using that key in every episode I watch. So I was thinking of a way so that I can launch MPV with a --profile option, that way the shader will only work in anime watch.
> 
> Please implement this feature in some upcoming release as it will be really helpful or tell me some way it could be done in the current release.

If this PR goes through you can run anime config and enter the number that is next to "watch" and now there should be an extra setting called "mpv_arguments". You can set it to --profile=anime4k if you have that profile and add other settings, I plan on making it so you could set different launch settings depending on the video quality and etc.

**Comment by akash-258** [comment]
@theCow61 Thank you so much, I just tested your commit and I can confirm it works just as I wished. May God bless you :1st_place_medal:

**Comment by theCow61** [comment]
@akash-258 No problem, I was actually wanting this feature too but never decided to do it myself until I found someone else wanting the feature too.

**Comment by akash-258** [comment]
@theCow61 So did you also felt a need to have different launch options for different anime in your list cuz some are in 480p and some in 1080p and both require different set of shaders to work well. But that may be just me getting greedy 😉

**Comment by theCow61** [comment]
> @theCow61 So did you also felt a need to have different launch options for different anime in your list cuz some are in 480p and some in 1080p and both require different set of shaders to work well. But that may be just me getting greedy 😉

That's exactly why I wanted this.
