### ISSUE TITLE
Description is either outdated or the program sources are as sources have not been updated in a while

### ISSUE THREAD

**Issue by TheNormalPeople** [anime-dl/anime-downloader#601]
**Describe the bug**

The Description is either outdated or the program is as some sources you say are in the program aren't. Many anime sites like darkanime and itsaturday don't even exist anymore. The description says that choices like a2zanime exists while only 4anime, anitube, anime8, animebinge, gurminder, animedaisuki, animeflix, animeflv, animefreak, animefree, animefrenzy, animekisa, animetake, animeonline360, animeout, animerush, animesimple, animesuge, animevibe, animixplay, darkanime, dbanimes, erai-raws, egyanime, fastani, itsaturday, justdubs, kickass, kissanimex, kisscartoon, 9anime, nyaa, putlockers, ryuanime, subsplease, twist.moe, tenshi.moe, vidstream, voiranime and vostfree exists.

**To reproduce**

```
anime dl "Fullmetal Alchemist" -q 1080p -p a2zanime
```

<details>
<summary>LOG</summary>

```



```

**Comment by AbdullahM0hamed** [comment]
Updated. We did have a2zanime, but it was removed in #327 and it somehow escaped us all to update the README to reflect that. Thanks for the catch.
