### ISSUE TITLE
Be able to seperate subs and dubs from content in like ryuanime and dubbedanime

### ISSUE THREAD

**Issue by H4rl00** [anime-dl/anime-downloader#602]
Be able to seperate subs and dubs from content in like ryuanime and dubbedanime as it uses a button to switch through them instead of having them as seperate titles

**Comment by ArjixGamer** [comment]
We already do that, please kindly take a look at the anime dl configuration.
We have an ``anime config`` command, use it navigate to ``siteconfig`` then to ``ryuanime`` then to ``version`` and set it to ``"dubbed"``
After that anime dl will instead use the dub,

**Comment by H4rl00** [comment]
Any way to make it more dynamic?

>

**Comment by AbdullahM0hamed** [comment]
Wdym by dynamic in this instance? If you mean being able to choose it whilst running the command then #619 would help with that
