### ISSUE TITLE
Like `set episodes_done`, is `set url` possible?

### ISSUE THREAD

**Issue by PROxZIMA** [anime-dl/anime-downloader#603]
So basically in my MAL XML list, AoT's final season was named as `Attack on Titan: The Final Season`. When I tried to set provider as `4anime`, the anime was removed from the list as no search results were found on 4anime for the exact title.

So like `set episodes_done`, is it possible to `set url` for an anime?

After that we can simply do `anime watch -u` to update the `_episode_urls`

**Comment by akash-258** [comment]
I also have doubts regarding this because sometimes even if the title doesn't match but slightly differs, changing the provider works, but sometimes it shows the "not found" error. But how would "set url" help here, we don't know what is the exact title of that anime on the other provider.

Experts please shed some light here.

**Comment by PROxZIMA** [comment]
@akash-258 In my case, I was importing a MAL list so all the list items had name but didn't had a url. So setting url of an anime (from one of the providers) will update its `_episode_urls`.

But I got your point about how will `set url` help when adding a new anime from terminal. But `set` command works for anime which are already in the list right.

**Comment by IguanasInPyjamas** [comment]
> @akash-258 In my case, I was importing a MAL list so all the list items had name but didn't had a url. So setting url of an anime (from one of the providers) will update its `_episode_urls`.
> 
> But I got your point about how will `set url` help when adding a new anime from terminal. But `set` command works for anime which are already in the list right.

This is where you use set provider.... That resets the anime in watch.
