### ISSUE TITLE
Watching anything on windows throws [WinError 2]

### ISSUE THREAD

**Issue by BlaNKtext** [anime-dl/anime-downloader#611]
**Describe the bug**

Trying to use the watch command does not work for me, it very well may be my own error, I'm using twist.moe as my provider and I create a list (Kizumonogatari Trilogy) and try to watch it, [WinError 2]. I do have mpv installed in my program files directory

**To reproduce**

```
anime watch

1

watch
```

<details>
<summary>LOG</summary>

```
[WinError 2]

or nothing and has me re-enter the command which does nothing (When run as admin)


```

**Comment by H4rl00** [comment]
I'd request launching it like this
open cmd as a user and not administrator. And input cd (path)
and then run anime watch

**Comment by IguanasInPyjamas** [comment]
win error 2 is file not found iirc, you probably need to add mpv to your path.

**Comment by BlaNKtext** [comment]
> I'd request launching it like this
> open cmd as a user and not administrator. And input cd (path)
> and then run anime watch

![image](https://user-images.githubusercontent.com/64222857/105636361-0d574480-5e36-11eb-9161-be2babd69ee8.png)
Doesnt seem to of worked, instead I get nothing? I do have mpv installed and working

**Comment by BlaNKtext** [comment]
> win error 2 is file not found iirc, you probably need to add mpv to your path.

Not entirely clear on what you mean by that, I do already have my mpv folder in the anime-dl folder
![image](https://user-images.githubusercontent.com/64222857/105636859-324cb700-5e38-11eb-90fb-45a63ddb2feb.png)

I also tried with the GUI and got a more informative(?) error
![image](https://user-images.githubusercontent.com/64222857/105636875-53150c80-5e38-11eb-9496-6a61dfc2e8cb.png)

**Comment by IguanasInPyjamas** [comment]
> > win error 2 is file not found iirc, you probably need to add mpv to your path.
> 
> Not entirely clear on what you mean by that, I do already have my mpv folder in the anime-dl folder
> ![image](https://user-images.githubusercontent.com/64222857/105636859-324cb700-5e38-11eb-90fb-45a63ddb2feb.png)
> 
> I also tried with the GUI and got a more informative(?) error
> ![image](https://user-images.githubusercontent.com/64222857/105636875-53150c80-5e38-11eb-9496-6a61dfc2e8cb.png)

https://www.google.com/search?sxsrf=ALeKk00csdYIQI_vVdiszqdiudspjv3FFA%3A1611507446638&ei=9qYNYJO2JpLzgQbS8Kb4DA&q=how+to+add+to+path+windows+10&oq=how+to+add+to+path+&gs_lcp=CgZwc3ktYWIQARgBMgIIADICCAAyAggAMgYIABAHEB4yAggAMgYIABAHEB4yBggAEAcQHjIGCAAQBxAeMgIIADICCAA6BwgjELADECc6BwgAELADEEM6BAgAEA1QqYMBWMy9AmDLzQJoCnACeAuAAc8NiAH8fZIBETAuMS4wLjEuMS4wLjQuMy41mAEAoAEBqgEHZ3dzLXdpesgBCsABAQ&sclient=psy-ab

**Comment by IguanasInPyjamas** [comment]
Add mpv to your path.

**Comment by BlaNKtext** [comment]
> Add mpv to your path.

And its fixed! thank you very much for your time, and have a great day/night/evening
