### ISSUE TITLE
Update issue using Shiro.is

### ISSUE THREAD

**Issue by akash-258** [anime-dl/anime-downloader#615]
**Describe the bug**
Updating an anime using 'shiro' provider gives this error
```
'AnimeInfo' object has no attribute 'token'
```

**To reproduce**
```
1) anime watch -n --provider=shiro
2) code geass
3) anime watch -u
```
[screenshot](https://ibb.co/2y3dHFN)

**Comment by nate-moo** [comment]
![image](https://user-images.githubusercontent.com/40650681/107104858-8751db00-67f1-11eb-9c36-d4794dcd202c.png)
same thing here, I'll take a look

**Comment by nate-moo** [comment]
it seems like it's an issue with shiro.is, imma ping @ArjixGamer as he was the one who made the provider

**Comment by akash-258** [comment]
I want to help in this project as well, but don't know where to begin. It would be really helpful if someone could make a tutorial explaining this project in brief and/or how a new site is added.

**Comment by ArjixGamer** [comment]
ill take a look into it

**Comment by ArjixGamer** [comment]
oh, i get it

**Comment by ArjixGamer** [comment]
will fix
