### ISSUE TITLE
ERROR: The read operation timed out

### ISSUE THREAD

**Issue by thereal-Stiven** [anime-dl/anime-downloader#663]
**Describe the bug**

I get this error while trying to download any anime. The first 4-8 episodes no problem and then this comes up

**To reproduce**

```
anime dl "golden boyl"
```

<details>
<summary>LOG</summary>

```
user99@user99-VirtualBox:~/Downloads/anime-downloader$ anime dl "golden boy"
anime: anime-downloader 5.0.9
+--------+--------------------------------------------+--------+
|      5 | Himitsu Kessha Taka no Tsume: Golden Spell |        |
|      4 | Chuubyou Gekihatsu Boy                     |        |
|      3 | Berserk Golden Arc Movies                  |        |
|      2 | Golden Boy (Dub)                           |        |
|      1 | Golden Boy                                 |        |
|--------+--------------------------------------------+--------|
|   SlNo | Title                                      | Meta   |
+--------+--------------------------------------------+--------+
Enter the anime no: [1]: 1
anime: Selected Golden Boy
anime: Extracting episode info from page
anime: Found anime: golden-boy
INFO:anime_downloader.commands.dl:Found anime: golden-boy
anime: Downloading to /home/user99/Downloads/anime-downloader
INFO:anime_downloader.commands.dl:Downloading to /home/user99/Downloads/anime-downloader
anime: Downloading golden-boy-1
INFO:anime_downloader.sites.anime:Downloading golden-boy-1
anime: ./golden-boy/golden-boy_1.mp4
INFO:anime_downloader.downloader.base_downloader:./golden-boy/golden-boy_1.mp4
 [*] 219.0 MB / 219.0 MB @ 2.8 MB/s [##################] [100%, 0s left]      

anime: Downloading golden-boy-2
INFO:anime_downloader.sites.anime:Downloading golden-boy-2
anime: ./golden-boy/golden-boy_2.mp4
INFO:anime_downloader.downloader.base_downloader:./golden-boy/golden-boy_2.mp4
 [*] 183.6 MB / 183.6 MB @ 29 kB/s [##################] [100%, 0s left]       
 [*] 183.6 MB / 183.6 MB @ 3.8 MB/s [##################] [100%, 0s left]    ]    
 [*] 183.6 MB / 183.6 MB @ 11.7 MB/s [##################] [100%, 0s left]        
 [*] 183.6 MB / 183.6 MB @ 27 kB/s [##################] [100%, 0s left]    ]    
ERROR: HTTP Error 0: The maximum retry attempts reached ([Errno 104] Connection reset by peer)



```

**Comment by ArjixGamer** [comment]
Nice Log
![image](https://user-images.githubusercontent.com/53124886/115112602-ede03b80-9f8e-11eb-9245-2011d953bb47.png)

**Comment by thereal-Stiven** [comment]
> Nice Log
> ![image](https://user-images.githubusercontent.com/53124886/115112602-ede03b80-9f8e-11eb-9245-2011d953bb47.png)

updated, tried the --log-level DEBUG did not work

**Comment by ArjixGamer** [comment]
> tried the --log-level DEBUG did not work

because you didnt use it properly
`--log-level` or in short `-ll` is an argument for the anime command, not the dl sub-command

It can be used like this:
``anime -ll DEBUG dl "golden boy"``

And, from the current log that you provided I can see that you are using the internal downloader in anime dl.
It is recommended that you use aria2 or wget.

You can use them by adding this argument to the dl command:
``-xd`` or ``--external-downloader`` and to use aria2 the value is be ``{aria2}`` or to use wget the value is ``{wget}``
e.g. ``anime dl "overlord" -xd "{aria2}"``

Or you can change the default downloader in the config.

You can do so by running the command ``anime config``.
Select ``dl``
Select ``external_downloader``
And input the value, for example ``"{aria2}"``


Note: Of course those downloaders are not provided by anime dl and must be installed from external sources.

PS: Anything that is highlighted (like ``this``) is to be taken as is.

**Comment by thereal-Stiven** [comment]
> > tried the --log-level DEBUG did not work
> 
> because you didnt use it properly
> `--log-level` or in short `-ll` is an argument for the anime command, not the dl sub-command
> 
> It can be used like this:
> `anime -ll DEBUG dl "golden boy"`
> 
> And, from the current log that you provided I can see that you are using the internal downloader in anime dl.
> It is recommended that you use aria2 or wget.
> 
> You can use them by adding this argument to the dl command:
> `-xd` or `--external-downloader` and to use aria2 the value is be `{aria2}` or to use wget the value is `{wget}`
> e.g. `anime dl "overlord" -xd "{aria2}"`
> 
> Or you can change the default downloader in the config.
> 
> You can do so by running the command `anime config`.
> Select `dl`
> Select `external_downloader`
> And input the value, for example `"{aria2}"`
> 
> Note: Of course those downloaders are not provided by anime dl and must be installed from external sources.
> 
> PS: Anything that is highlighted (like `this`) is to be taken as is.

sorry for the late reply i used `anime -ll DEBUG dl "golden boy"` and got the following
`Usage: anime command [OPTIONS] ANIME_URL

Error: Invalid value for '--fallback-qualities' / '-fq': None`

> 

>

**Comment by ArjixGamer** [comment]
that is because your configuration is invalid
not an error on our part

**Comment by thereal-Stiven** [comment]
the config is default i just changed what you told me in the comment before.

**Comment by Gizmofire** [comment]
It seems the error your getting is your fallback qualities are set to a not expected value. If you did not mess with them by default they should be `['720p', '480p', '360p']`. So probably change your config.json file or use `anime config` to change it.

**Comment by thereal-Stiven** [comment]
> It seems the error your getting is your fallback qualities are set to a not expected value. If you did not mess with them by default they should be `['720p', '480p', '360p']`. So probably change your config.json file or use `anime config` to change it.

<img width="822" alt="Screenshot 2021-04-25 at 02 09 41" src="https://user-images.githubusercontent.com/69769400/115976164-5b7e0000-a56b-11eb-9136-961966699348.png">

**Comment by Gizmofire** [comment]
Yeah. Your calling for 1080p as the fallback quality, which is the main quality but the fallback quality should be set to `['720p', '480p', '360p']`. This is so if anime dl were not to find the 1080p quality, anime it would result to the next value on the list which would be 720 then to 480 and so on. So if you were to run what you have right now it errors out. BTW quality and fallback qualities should not be the same.

**Comment by thereal-Stiven** [comment]
> Yeah. Your calling for 1080p as the fallback quality, which is the main quality but the fallback quality should be set to `['720p', '480p', '360p']`. This is so if anime dl were not to find the 1080p quality, anime it would result to the next value on the list which would be 720 then to 480 and so on. So if you were to run what you have right now it errors out. BTW quality and fallback qualities should not be the same.

<img width="822" alt="Screenshot 2021-04-25 at 02 17 12" src="https://user-images.githubusercontent.com/69769400/115976259-5ff6e880-a56c-11eb-82e7-2382233a9364.png">
Yes the fallback is the same as you said, like I said i havent changed anything except the aria2, installed it with git clone cd into it and "python setup.py install" thats why I am wondering why it doesnt work

**Comment by Gizmofire** [comment]
wait im trppin. To be honest, I never had to run the setup.py, I just run the `pip install` for anime-dl and things were set.  Assuming aria2 was installed properly (setting environment variables after unzipping or whatever installation), my recommendation is to set it back to slow downloading property. Although, I may be very wrong because I have no idea what a mac is nor ever owned one. Have a nice rest of your day, hopefully this isn't an emgency thing.

**Comment by thereal-Stiven** [comment]
no its not as long as i get it to work sometimes in the near future, ill test the pip install version, maybe something was messed up.
brgds.

**Comment by thereal-Stiven** [comment]
Is there an uninstall script or smtn like that?

**Comment by thereal-Stiven** [comment]
nvm i just force installed it with pip and it seems to work somehow, i am trying it out now because sometimes I got an error and the last 1-3 episodes weren't downloaded. If it works ill close the issue and thank you guys.
BRGDS.
