### ISSUE TITLE
Facing an error while downloading episodes

### ISSUE THREAD

**Issue by PranavThampi** [anime-dl/anime-downloader#664]
**Describe the bug**

I am using this program to download the anime Naruto Shippuden. While downloading it, the program gets an error while downloading a few episodes due to which it terminates. In order to understand the error I used --log-level DEBUG but get the error that no such option exists. Kindly help. Also please make the installation stupid friendly. I somehow managed to install it as a CLI program but didn't understand how to do the GUI installation. The youtube video has been removed so kindly share the video some other way.

**To reproduce**

anime dl naruto -e 130:200 -d -q 1080p

![image](https://user-images.githubusercontent.com/57982907/114819277-d95b4200-9dda-11eb-80a5-61c7459ebc00.png)
![image](https://user-images.githubusercontent.com/57982907/114819306-e37d4080-9dda-11eb-822e-5ec487860430.png)

<details>
<summary>LOG</summary>

```



```

**Comment by ArjixGamer** [comment]
um, --log-level is an option but its for the anime command, not for the dl sub command

so to get that error you must have used it with dl
the proper usage is below:
```cmd
anime --log-level DEBUG dl naruto -e 130:200 -d -q 1080p
```

PS: I just noticed that you had some screenshot markdown but it was in a code block so it didnt load the images :p
      So I was correct, you used the log level on dl rather than using it on anime

**Comment by PranavThampi** [comment]
> um, --log-level is an option but its for the anime command, not for the dl sub command
> 
> so to get that error you must have used it with dl
> the proper usage is below:
> 
> ```batchfile
> anime --log-level DEBUG dl naruto -e 130:200 -d -q 1080p
> ```
> 
> PS: I just noticed that you had some screenshot markdown but it was in a code block so it didnt load the images :p
> So I was correct, you used the log level on dl rather than using it on anime

Kindly check.  The image is visible now

**Comment by ArjixGamer** [comment]
> Kindly check. The image is visible now

Um, I already viewed the images, I just copy pasted the links.
Can you properly give log this time?

**Comment by PranavThampi** [comment]
> > Kindly check. The image is visible now
> 
> Um, I already viewed the images, I just copy pasted the links.
> Can you properly give log this time?

Appreciate you taking the time but it seems to be working now.
