### ISSUE TITLE
Graphical User Interface (GUI)

### ISSUE THREAD

**Issue by dothackjhe** [anime-dl/anime-downloader#666]
Cannot the developer make the process of using this application more simplified and user-friendly by creating a graphical user interface for it? 

I've personally seen programs that started off using the command line interface to be functional and eventually transform into a full blown, easy-to-use app by having a GUI to it.

**Comment by IguanasInPyjamas** [comment]
There is.

**Comment by dothackjhe** [comment]
Mind telling me about it?

I'm literally new to this.

**Comment by Gizmofire** [comment]
`anime gui` is the command you're looking for. Anime-dl is mostly CLI based so if u have any problems with the GUI, I recommend looking at the docs or using `anime dl --help`. Have a nice day!
