### ISSUE TITLE
animefreak stopped working

### ISSUE THREAD

**Issue by rubiin** [anime-dl/anime-downloader#676]
Upto last week i was using animefreak to download anime. Now when i choose the option,I can see the anime list however cannot download the anime. Gives resource not found

**Comment by AbdullahM0hamed** [comment]
I have tested, and it works just fine. Are you perhaps getting that from aria2c (it often does that, but downloads nonetheless) - perhaps you could attach a screenshot?

**Comment by rubiin** [comment]
sure let me attach a screenshot
