### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by thereal-Stiven** [anime-dl/anime-downloader#694]
Hello once again I got this error message 
`
ERROR: object of type 'CachedResponse' has no len()
`
here the full terminal output
![Screenshot from 2021-06-26 20-56-01](https://user-images.githubusercontent.com/69769400/123522981-2ef87880-d6c1-11eb-9afd-0075981aa284.png)

Sadly I dont know if there is any Debug function or any logs.
BR.

**Comment by LetsChill** [comment]
same issue happens to me but with random animes, i am trying to download demon slayer as well and it response to me like this. all providers does the same.
