### ISSUE TITLE
Add simply.moe

### ISSUE THREAD

**Issue by SelectLOL1** [anime-dl/anime-downloader#702]
Hello, simply.moe is a great site to stream anime. It offers great quality, fast stream and download. Thx for the great work, keep it up.

**Comment by ArjixWasTaken** [comment]
...is this a prank?

**Comment by SelectLOL1** [comment]
Why do you mean that? @ArjixWasTaken

**Comment by AbdullahM0hamed** [comment]
@SelectLOL1 go to https://simply.moe now, it says it had closed down

**Comment by SelectLOL1** [comment]
Oh yes, it is really down...sorry
