### ISSUE TITLE
Help me Nothings Working

### ISSUE THREAD

**Issue by NevGi-cpu** [anime-dl/anime-downloader#713]
1. when downloading anime in 480p, it will download in the highest resolution instead, I used:
anime dl <url> -e 1:12 -q 480p
2. Animixplay, 9anime, gogoanime, etc not working
3. I can still download anime in the highest resolution but I wanted to download in 480p because of the low free space on my drive

**Comment by ArjixWasTaken** [comment]
Yeah uhh
Most of the providers dont support multiple resolutions....
So uhh, the only advice I can give is to use another provider...
For example an excellent provider that supports multiple qualities is tenshi.moe
Although its library is small.
