### ISSUE TITLE
Docs refer to vn-ki/anime-downloader even though it has moved to anime-dl/anime-downloader

### ISSUE THREAD

**Issue by sreekaransrinath** [anime-dl/anime-downloader#718]
**Describe the bug**
Docs refer to vn-ki/anime-downloader even though it has moved to anime-dl/anime-downloader

**To reproduce**
Visible at:
https://anime-downlader.readthedocs.io/en/latest/usage/installation.html and multiple other locations

**Comment by ArjixWasTaken** [comment]
Doesn't matter since github redirects to the new link.
