### ISSUE TITLE
WinError 2

### ISSUE THREAD

**Issue by UltraJew** [anime-dl/anime-downloader#727]
**Describe the bug**

**To reproduce**

Could someone tell me where anime-dl installs to when using choco on windows and specifically how I can add mpv to path to fix this?

**Comment by ArjixWasTaken** [comment]
choco doesnt install anime dl
choco installs python

and using python's pip we install anime dl

so uhh, you can run

```python
import anime_downloader
print(anime_downloader.__file__)
```
to get the folder where the code is stored at

as for how to add smth to the PATH, look at https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/

**Comment by UltraJew** [comment]
thanks
