### ISSUE TITLE
[ERROR] : 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by vtomes** [anime-dl/anime-downloader#738]
I am trying to download from animeflix but every time I try downloading, it just fives me this error:

_[INFO] : AnimeFlix URL detected...
[ERROR] : 'NoneType' object has no attribute 'group'
[ERROR] : Something went wrong! Please close and restart Anime Downloader to retry!_

I can't figure out what to do. 

Screenshot: https://imgur.com/a/2y4wriy

**Comment by vtomes** [comment]
Ahhhhhh, fuck. Now I feel like an idiot. Sorry :D. I had multiple repos open and messed it up. :D

**Comment by ArjixWasTaken** [comment]
It's ok, don't worry, both are dead projects either way.
