### ISSUE TITLE
How to reset episode number, or go back one episode

### ISSUE THREAD

**Issue by rgeorge04** [anime-dl/anime-downloader#743]
i have my anime watch list but if i didn't watch the episode fully, next time i watch again, it streams the next one, i don't see a option for selection which episode to run specifically. Help?

**Comment by ArjixWasTaken** [comment]
Wow an active user!
What a rare sight...

Anyways, the command is `set episodes_done=13` where 13 is the number you want

**Comment by rgeorge04** [comment]
Thanks :)
